### PR TITLE
Add Apache 2.0 License

### PR DESCRIPTION
**Pull request by csrwng**
Adds LICENSE file to this repository

### CODE REVIEW

**Comment by wking** [comment]
Do we want `README.md` and/or `CONTRIBUTING.md` wording to make the grant explicit?  Vs. relying on the presence of a `LICENSE` file to implicitly grant access under the license's terms.  I'm also fine punting this point to follow-up discussion.

And I explicitly release all of my previous contributions to this repository under the Apache License, Version 2.0, if any of them were significant enough to be copyrightable in the first place ;).

**Comment by LalatenduMohanty** [comment]
> Do we want `README.md` and/or `CONTRIBUTING.md` wording to make the grant explicit? Vs. relying on the presence of a `LICENSE` file to implicitly grant access under the license's terms. I'm also fine punting this point to follow-up discussion.

This came to my mind when I was reviewing the PR as well. Cross checked couple of other repositories and I did not see teh license explicitly mentioned in the readme. So I think this PR as it is , should be fine.

**Pull request merged**
